<?php

namespace Database\Seeders;

use App\Models\POCase;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Carbon;

class CaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $statuses = ['Input Required', 'In Review', 'Approved', 'Awaiting Submission'];

        for ($i = 0; $i < 1000; $i++) {
            $random_date = Carbon::createFromTimestampUTC(rand(0, time()));

            $case = new POCase;
            $case->name = $this->randomName();
            $case->status = Arr::random($statuses);
            $case->user_id = 1;
            $case->case_type_id = rand(1, 2);
            $case->created_at = $random_date;
            $case->updated_at = $random_date;

            $case->save();
        }
    }

    public function randomName()
    {
        return Arr::random([
            'Cameron Bowman',
            'Carlo Travis',
            'Paxton Burgess',
            'Liana Garcia',
            'Giovanny Cherry',
            'Cole Ortiz',
            'Oswaldo Love',
            'Janet Newman',
            'Braydon Graves',
            'Kenya Liu',
            'Rowan Bartlett',
            'Isabella Rivera',
            'Tiana Dodson',
            'Claudia Rodgers',
            'Greyson Herrera',
            'Davin Jordan',
            'Jaylee Washington',
            'Imani York',
            'Jazmyn Randall',
            'Anastasia Frost',
            'Davis Spence',
            'Messiah Chen',
            'Abbey Evans',
            'Stephany Mosley',
            'Keyon May',
            'Yair Kane',
            'Cameron Hancock',
            'Angela Ashley',
            'Kennedi Whitney',
            'Britney Williams',
            'Harley Lam',
            'Camryn Heath',
            'Jimmy Preston',
            'Laura Villanueva',
            'Milton Donaldson',
            'Bryce Robinson',
            'Cassandra Moody',
            'Leonard Fisher',
            'Abraham Ortiz',
            'Jennifer Galloway',
            'Kadin Cowan',
            'Deborah Duarte',
            'Rose Lowery',
            'Jaslene Hale',
            'Jamie Bender',
            'Larry Lara',
            'Jeffery Hill',
            'Rodolfo Francis',
            'Skyler Knox',
            'Anya Chen',
            'Zaria Humphrey',
            'Avery Schmidt',
            'Lyric Olson',
            'Cornelius Gallagher',
            'Lilian Lynch',
            'Kendal Acosta',
            'Jeremy Hughes',
            'Hailie Durham',
            'Reece Swanson',
            'Valentina Esparza',
            'Dominique Pittman',
            'Joseph Vaughn',
            'Toby Wood',
            'Dominic Lamb',
            'Kayden Blackburn',
            'Broderick Conrad',
            'Maurice Hood',
            'Mercedes Moody',
            'Roger Hendricks',
            'Tori Bonilla',
            'Genevieve Coleman',
            'Zaid Buck',
            'Trent Mullins',
            'Lyric Neal',
            'Gage Schroeder',
            'Angela Lin',
            'Donavan Beard',
            'Krista Andersen',
            'Jeffery Santana',
            'Colby Ellison',
            'Axel Russo',
            'Hunter Barber',
            'Kali Chen',
            'Monserrat Murillo',
            'Wilson Vaughan',
            'Rey Barrett',
            'Rose Daugherty',
            'Ethan York',
            'Alicia Andersen',
            'Angeline Frederick',
            'Jameson Mccullough',
            'Valerie Marks',
            'Cyrus Kidd',
            'Kameron Barnes',
            'Jayvon Bond',
            'Alma Hood',
            'Isaiah Santos',
            'Dangelo Hamilton',
            'Veronica Escobar',
            'Marlene Cole',
            'Koen Valenzuela',
            'Sergio Mack',
            'Adeline Wright',
            'Miguel Strong',
            'Ashton Santos',
            'Bronson Zimmerman',
            'Lilyana Costa',
            'River Clark',
            'Aurora King',
            'Luciano Rivas',
            'Damien Krause',
            'Paul Woods',
            'Jazlynn Robles',
            'Rocco Morrow',
            'Abram Beasley',
            'Gracelyn Frederick',
            'Kristian Wilkerson',
            'Juliette Singh',
            'Jaxon Morse',
            'Emmalee Thompson',
            'Anika Huerta',
            'Cristopher Meyer',
            'Jeffery Macias',
            'Francisco Chung',
            'Shaun Grimes',
            'Karissa Christian',
            'Raina Galvan',
            'Judah Aguirre',
            'Itzel Rosales',
            'Kamron Rush',
            'Moses Henderson',
            'Deshawn Summers',
            'Parker Lawrence',
            'Angie Crosby',
            'Amara Bartlett',
            'Donavan Chandler',
            'Ishaan Aguirre',
            'Kyan Schroeder',
            'Kaliyah Ayers',
            'Tatum Schmidt',
            'Dominick Estrada',
            'Donald Haynes',
            'Sienna Morse',
            'Jett Contreras',
            'Janessa Willis',
            'Freddy Arnold',
            'Kaila Hendricks',
            'Steven Blake',
            'Jackson Blankenship',
            'Campbell Lucas',
            'Yasmine Mcfarland',
            'Rachael Carr',
            'Liberty Montoya',
            'Emanuel Matthews',
            'Mateo Bray',
            'Cristopher Patton',
            'Princess Camacho',
            'Javier Malone',
            'Malakai Fox',
            'Thomas Allen',
            'Thaddeus Acevedo',
            'Omar Mann',
            'Dayami Rivera',
            'Iyana Delacruz',
            'Melvin Sheppard',
            'Rosemary Carson',
            'Victor Osborn',
            'Maia Garner',
            'Tyrell Fritz',
            'Ariella Gentry',
            'Aracely Graves',
            'Catalina Morris',
            'Dalton Hardy',
            'Aaden Rose',
            'Matias Hickman',
            'Yazmin Zavala',
            'Cassie Farmer',
            'Hailee Barrera',
            'Julie Walton',
            'Whitney Clarke',
            'Aliyah Hutchinson',
            'Jaiden Mendoza',
            'Amina Blanchard',
            'Chance Rivas',
            'Kendal Moreno',
            'Joey Hanson',
            'Daniella Reilly',
            'Kade Hughes',
            'Dante Logan',
            'Blaine Dunn',
            'Jonah Summers',
            'Rachael Gates',
            'Mylie Collier',
            'Bailey Powell',
            'Mohammed Schultz',
            'Aliana Rush',
            'Carson Rocha',
            'Noel Galloway',
            'Derrick Rocha',
            'Terry Rogers',
        ]);
    }
}
