name: Deploy

on:
  push:
    branches: master

env:
  APP_ENV: production
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Up Deployer
        run: curl -LO https://deployer.org/deployer.phar && mv deployer.phar bin/dep && sudo chmod +x bin/dep

      - name: Deploy
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
          dep: deploy